                      List of relations
  Schema  |           Name           |   Type   |    Owner    
----------+--------------------------+----------+-------------
 public   | geography_columns        | view     | hello_flask
 public   | geometry_columns         | view     | hello_flask
 public   | spatial_ref_sys          | table    | hello_flask
 public   | tweet_urls               | table    | hello_flask
 public   | tweets                   | table    | hello_flask
 public   | urls                     | table    | hello_flask
 public   | urls_id_urls_seq         | sequence | hello_flask
 public   | users                    | table    | hello_flask
 tiger    | addr                     | table    | hello_flask
 tiger    | addr_gid_seq             | sequence | hello_flask
 tiger    | addrfeat                 | table    | hello_flask
 tiger    | addrfeat_gid_seq         | sequence | hello_flask
 tiger    | bg                       | table    | hello_flask
 tiger    | bg_gid_seq               | sequence | hello_flask
 tiger    | county                   | table    | hello_flask
 tiger    | county_gid_seq           | sequence | hello_flask
 tiger    | county_lookup            | table    | hello_flask
 tiger    | countysub_lookup         | table    | hello_flask
 tiger    | cousub                   | table    | hello_flask
 tiger    | cousub_gid_seq           | sequence | hello_flask
 tiger    | direction_lookup         | table    | hello_flask
 tiger    | edges                    | table    | hello_flask
 tiger    | edges_gid_seq            | sequence | hello_flask
 tiger    | faces                    | table    | hello_flask
 tiger    | faces_gid_seq            | sequence | hello_flask
 tiger    | featnames                | table    | hello_flask
 tiger    | featnames_gid_seq        | sequence | hello_flask
 tiger    | geocode_settings         | table    | hello_flask
 tiger    | geocode_settings_default | table    | hello_flask
 tiger    | loader_lookuptables      | table    | hello_flask
 tiger    | loader_platform          | table    | hello_flask
 tiger    | loader_variables         | table    | hello_flask
 tiger    | pagc_gaz                 | table    | hello_flask
 tiger    | pagc_gaz_id_seq          | sequence | hello_flask
 tiger    | pagc_lex                 | table    | hello_flask
 tiger    | pagc_lex_id_seq          | sequence | hello_flask
 tiger    | pagc_rules               | table    | hello_flask
 tiger    | pagc_rules_id_seq        | sequence | hello_flask
 tiger    | place                    | table    | hello_flask
 tiger    | place_gid_seq            | sequence | hello_flask
 tiger    | place_lookup             | table    | hello_flask
 tiger    | secondary_unit_lookup    | table    | hello_flask
 tiger    | state                    | table    | hello_flask
 tiger    | state_gid_seq            | sequence | hello_flask
 tiger    | state_lookup             | table    | hello_flask
 tiger    | street_type_lookup       | table    | hello_flask
 tiger    | tabblock                 | table    | hello_flask
 tiger    | tabblock20               | table    | hello_flask
 tiger    | tabblock_gid_seq         | sequence | hello_flask
 tiger    | tract                    | table    | hello_flask
 tiger    | tract_gid_seq            | sequence | hello_flask
 tiger    | zcta5                    | table    | hello_flask
 tiger    | zcta5_gid_seq            | sequence | hello_flask
 tiger    | zip_lookup               | table    | hello_flask
 tiger    | zip_lookup_all           | table    | hello_flask
 tiger    | zip_lookup_base          | table    | hello_flask
 tiger    | zip_state                | table    | hello_flask
 tiger    | zip_state_loc            | table    | hello_flask
 topology | layer                    | table    | hello_flask
 topology | topology                 | table    | hello_flask
 topology | topology_id_seq          | sequence | hello_flask
(61 rows)

